updated

diff --git a/.github/workflows/sanity_checks.yml b/.github/workflows/sanity_checks.yml
--- a/.github/workflows/sanity_checks.yml
+++ b/.github/workflows/sanity_checks.yml
@@ -50,6 +50,107 @@ jobs:
           if [[ "$steps_flag" == "false" ]]; then
             exit 1
           fi
+  File_Name_Standard:
+    name: Check for file naming convention
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Get changed files
+        id: changed-files
+        uses: tj-actions/changed-files@v44
+      
+      - name: List all changed files
+        env:
+          MODIFIED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
+        run: |
+          for file in "${MODIFIED_FILES}"; do
+            echo "$file was changed"
+          done
+          echo "MODIFIED_FILES=$MODIFIED_FILES" >> $GITHUB_ENV
+      - name: Print files
+        run: echo "${{ env.MODIFIED_FILES }}"
+      
+      - name: Get the list of assessment tools
+        run: |
+          tools=$(cat .github/scripts/assessment_tools.txt | tr '\n' '|')
+          tools=${tools%|}
+          echo "ASSESSMENT_TOOLS=$(echo "$tools")" >> $GITHUB_ENV
+      
+      - name: Check playbook naming convention
+        run: |
+          file_flag=false
+          for file in $(echo "${{ env.MODIFIED_FILES }}" | grep -E "${{ env.ASSESSMENT_TOOLS }}" | grep -e ".*playbook.sh"); do  
+            prefix=$(echo "$file" | cut -d "-" -f 1)
+            tool=$(echo "$file" | cut -d "-" -f 2)
+            version=$(echo "$file" | cut -d "-" -f 3)
+            suffix=$(echo "$file" | cut -d "-" -f 4)
+            extension=$(echo "$file" | cut -d "." -f 2)
+            if [[ "$prefix" != "besman" ]];
+            then
+              echo -e "\e[31mMissing besman prefix in \e[33m$file\e[0m"
+              file_flag=true
+            fi
+            if ! (echo $tool | grep -E "${{ env.ASSESSMENT_TOOLS }}")
+            then
+              echo -e "\e[31mUnknown tool \e[33m$tool\e[31m in \e[33m$file\e[0m"
+              file_flag=true
+            fi
+            if [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]];then
+              echo -e "\e[31mIncorrect version format[0m"
+              file_flag=true
+            fi
+            if [[ "$suffix" != "playbook" ]];
+            then
+              echo -e "\e[31mMissing playbook suffix in \e[33m$file\e[0m"
+              file_flag=true
+            fi
+            if ! (echo $extension | grep "sh" )
+            then
+              echo -e "\e[31mIncorrect extension[0m"
+              file_flag=true
+            fi
+          done
+          if [[ "$file_flag" == "true" ]]; then
+            exit 1
+          fi
+      - name: Check steps file naming convention
+        run: |
+            file_flag=false
+            for file in $(echo "${{ env.MODIFIED_FILES }}" | grep -E "${{ env.ASSESSMENT_TOOLS }}" | grep -e ".*steps*"); do  
+              prefix=$(echo "$file" | cut -d "-" -f 1)
+              tool=$(echo "$file" | cut -d "-" -f 2)
+              version=$(echo "$file" | cut -d "-" -f 3)
+              suffix=$(echo "$file" | cut -d "-" -f 4)
+              extension=$(echo "$file" | cut -d "." -f 2)
+              if [[ "$prefix" != "besman" ]];
+              then
+                echo -e "\e[31mMissing besman prefix in \e[33m$file\e[0m"
+                file_flag=true
+              fi
+              if ! (echo $tool | grep -E "${{ env.ASSESSMENT_TOOLS }}")
+              then
+                echo -e "\e[31mUnknown tool \e[33m$tool\e[31m in \e[33m$file\e[0m"
+                file_flag=true
+              fi
+              if [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]];then
+                echo -e "\e[31mIncorrect version format[0m"
+                file_flag=true
+              fi
+              if [[ "$suffix" != "steps" ]];
+              then
+                echo -e "\e[31mMissing playbook suffix in \e[33m$file\e[0m"
+                file_flag=true
+              fi
+              if ! (echo $extension | grep -e "sh" -e "md" -e "ipynb" )
+              then
+                echo -e "\e[31mIncorrect extension[0m"
+                file_flag=true
+              fi
+            done
+            if [[ "$file_flag" == "true" ]]; then
+              exit 1
+            fi
+
   Required_functions:
     name: Checking for required functions
     runs-on: ubuntu-latest
