Updated

diff --git a/.github/workflows/sanity_checks.yml b/.github/workflows/sanity_checks.yml
--- a/.github/workflows/sanity_checks.yml
+++ b/.github/workflows/sanity_checks.yml
@@ -21,79 +21,104 @@ jobs:
         env:
           MODIFIED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
         run: |
+          for file in "${{ env.MODIFIED_FILES }}"; do
+            echo "$file was changed"
+          done
+          echo "MODIFIED_FILES=${{ env.MODIFIED_FILES }}" >> $GITHUB_ENV
+
+      - name: Print files
+        run: echo "${{ env.MODIFIED_FILES }}"
+      
+      - name: Get the list of assessment tools
+        run: |
+          tools=$(cat .github/scripts/assessment_tools.txt | tr '\n' '|')
+          tools=${tools%|}
+          echo "ASSESSMENT_TOOLS=$(echo "$tools")" >> $GITHUB_ENV
+
+      
+      - name: dir
+        run: pwd
+      
+      # - name: Check for steps file
+      #   run: 
+      #     check_flag=false
+      #     for file in $(echo "${{ env.MODIFIED_FILES }}" | grep -E "${{ env.ASSESSMENT_TOOLS }}" | grep '\-playbook\.sh$');
+      #     do
+      #       toolname=$(echo "$file" | cut -d "-" -f 2)
+      #       version=$(echo "$file" | cut -d "-" -f 1)
+      #       if ! echo "${{ env.MODIFIED_FILES }}" | grep -q "besman-$toolname-$version-steps"
+      #       then
+      #         flag=true
+      #       fi
+      #       if ! ls -R . | grep -q "besman-$toolname-$version-steps"
+      #       then
+      #         flag=true
+      #       fi
+
+      #     done
+
+  # Uncomment below job
+  Required_functions:
+    name: Checking for required functions
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Get changed files
+        id: changed-files
+        uses: tj-actions/changed-files@v44
+      
+      - name: List all changed files
+        env:
+          MODIFIED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
+        run: |
           for file in "${MODIFIED_FILES}"; do
             echo "$file was changed"
           done
           echo "MODIFIED_FILES=$MODIFIED_FILES" >> $GITHUB_ENV
       - name: Print files
         run: echo "${{ env.MODIFIED_FILES }}"
-      
-      - name: dir
-        run: pwd
-      
-
-## Uncomment below job
-  # Required_functions:
-  #   name: Checking for required functions
-  #   runs-on: ubuntu-latest
-
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v2
-
-  #     - name: Get changed files
-  #       id: changed-files
-  #       uses: tj-actions/changed-files@v44
-      
-  #     - name: List all changed files
-  #       env:
-  #         MODIFIED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
-  #       run: |
-  #         for file in "${MODIFIED_FILES}"; do
-  #           echo "$file was changed"
-  #         done
-  #         echo "MODIFIED_FILES=$MODIFIED_FILES" >> $GITHUB_ENV
-  #     - name: Print files
-  #       run: echo "${{ env.MODIFIED_FILES }}"
 
         
-  #     - name: Get the list of required functions
-  #       id: get_functions
-  #       run: |
-  #         functions=$(cat .github/scripts/playbook_functions.txt)
-  #         echo "PLAYBOOK_FUNCTIONS=$(echo "$functions" | tr '\n' ' ')" >> $GITHUB_ENV
+      - name: Get the list of required functions
+        id: get_functions
+        run: |
+          functions=$(cat .github/scripts/playbook_functions.txt)
+          echo "PLAYBOOK_FUNCTIONS=$(echo "$functions" | tr '\n' ' ')" >> $GITHUB_ENV
 
       
-  #     - name: Get the list of assessment tools
-  #       run: |
-  #         tools=$(cat .github/scripts/assessment_tools.txt | tr '\n' '|')
-  #         tools=${tools%|}
-  #         echo "ASSESSMENT_TOOLS=$(echo "$tools")" >> $GITHUB_ENV
+      - name: Get the list of assessment tools
+        run: |
+          tools=$(cat .github/scripts/assessment_tools.txt | tr '\n' '|')
+          tools=${tools%|}
+          echo "ASSESSMENT_TOOLS=$(echo "$tools")" >> $GITHUB_ENV
 
-  #     - name: Print the list of required functions
-  #       run: echo "Required functions= ${{ env.PLAYBOOK_FUNCTIONS }}"
+      - name: Print the list of required functions
+        run: echo "Required functions= ${{ env.PLAYBOOK_FUNCTIONS }}"
 
-  #     - name: Print the list of required tools
-  #       run: echo "Required tools= ${{ env.ASSESSMENT_TOOLS }}"
+      - name: Print the list of required tools
+        run: echo "Required tools= ${{ env.ASSESSMENT_TOOLS }}"
 
-  #     - name: Check for required functions
-  #       run: |
-  #         function_flag=false
-  #         for file in $(echo "${{ env.MODIFIED_FILES }}" | grep -E "${{ env.ASSESSMENT_TOOLS }}" | grep '\-playbook\.sh$'); do
-  #           # Check if the file ends with "-playbook.sh"
-  #           for f in ${{ env.PLAYBOOK_FUNCTIONS }}; do
+      - name: Check for required functions
+        run: |
+          function_flag=false
+          for file in $(echo "${{ env.MODIFIED_FILES }}" | grep -E "${{ env.ASSESSMENT_TOOLS }}" | grep '\-playbook\.sh$'); do
+            # Check if the file ends with "-playbook.sh"
+            for f in ${{ env.PLAYBOOK_FUNCTIONS }}; do
 
-  #             if ! grep -q -w "function $f" $file
-  #             then
-  #               echo -e "\e[31mMissing function \e[33m$f\e[31m in \e[33m$file\e[0m"
-  #               function_flag=true
-  #             fi
-  #           done
-  #         done
-  #         if [[ $function_flag == true ]] 
-  #         then
-  #           exit 1
-  #         fi
+              if ! grep -q -w "function $f" $file
+              then
+                echo -e "\e[31mMissing function \e[33m$f\e[31m in \e[33m$file\e[0m"
+                function_flag=true
+              fi
+            done
+          done
+          if [[ $function_flag == true ]] 
+          then
+            exit 1
+          fi
 
   # Check_naming_convention:
   #   name: Check file naming conention
