Updated

diff --git a/.github/workflows/sanity_checks.yml b/.github/workflows/sanity_checks.yml
--- a/.github/workflows/sanity_checks.yml
+++ b/.github/workflows/sanity_checks.yml
@@ -105,47 +105,70 @@ jobs:
             fi
           done
   
-  # Check_if_metadata_update:
-  #   name: Checking for playbook in metadata
-  #   runs-on: ubuntu-latest
-  #   needs: 
-  #     - Required_files
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v2
+  Check_if_metadata_update:
+    name: Checking for playbook in metadata
+    runs-on: ubuntu-latest
+    needs: 
+      - Required_files
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
       
-  #     - name: Get changed files
-  #       id: changed-files
-  #       uses: tj-actions/changed-files@v44
+      - name: Get changed files
+        id: changed-files
+        uses: tj-actions/changed-files@v44
       
-  #     - name: List all changed files
-  #       env:
-  #         MODIFIED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
-  #       run: |
-  #         for file in "${MODIFIED_FILES}"; do
-  #           echo "$file was changed"
-  #         done
-  #         echo "MODIFIED_FILES=$MODIFIED_FILES" >> $GITHUB_ENV
-  #     - name: Print files
-  #       run: echo "${{ env.MODIFIED_FILES }}"
+      - name: List all changed files
+        env:
+          MODIFIED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
+        run: |
+          for file in "${MODIFIED_FILES}"; do
+            echo "$file was changed"
+          done
+          echo "MODIFIED_FILES=$MODIFIED_FILES" >> $GITHUB_ENV
+      - name: Print files
+        run: echo "${{ env.MODIFIED_FILES }}"
       
-  #     - name: Get the list of assessment tools
-  #       run: |
-  #         tools=$(cat /home/runner/work/besecure-playbooks-store/besecure-playbooks-store/.github/scripts/assessment_tools.txt | tr '\n' '|')
-  #         tools=${tools%|}
-  #         echo "ASSESSMENT_TOOLS=$(echo "$tools")" >> $GITHUB_ENV
+      - name: Get the list of assessment tools
+        run: |
+          tools=$(cat /home/runner/work/besecure-playbooks-store/besecure-playbooks-store/.github/scripts/assessment_tools.txt | tr '\n' '|')
+          tools=${tools%|}
+          echo "ASSESSMENT_TOOLS=$(echo "$tools")" >> $GITHUB_ENV
       
-  #     - name: Print the list of required tools
-  #       run: echo "Required tools= ${{ env.ASSESSMENT_TOOLS }}"
+      - name: Print the list of required tools
+        run: echo "Required tools= ${{ env.ASSESSMENT_TOOLS }}"
 
-  #     - name: Install jq
-  #       run: sudo apt-get update && sudo apt-get install jq -y
+      - name: Install jq
+        run: sudo apt-get update && sudo apt-get install jq -y
       
-  #     - name: Check for metadata file
-  #       run: |
-  #         if echo "${{ env.MODIFIED_FILES }}" | grep -q "playbook-metadata.json"; then
-  #           json_file_path
-  #         fi  
+      - name: Check for metadata file
+        run: |
+          metadata_json_path=""
+          if echo "${{ env.MODIFIED_FILES }}" | grep -q "playbook-metadata.json"; then
+            for file in "${{ env.MODIFIED_FILES }}"; do
+              if [[ "$file" == "playbook-metadata.json" ]]
+              then
+                metadata_json_path="$file"
+              fi
+            done
+          else
+            metadata_json_path="/home/runner/work/besecure-playbooks-store/besecure-playbooks-store/playbook-metadata.json"
+          fi
+
+          for file in $(echo "${{env.MODIFIED_FILES}}"); do
+            if [[ $file =~ playbooks\/(.*)-(.*)-(.*)-((playbook\.sh)|(steps\.(sh|md|ipynb)))$ ]]; then
+              name=$(echo $file | cut -d "/" -f 2 | cut -d "-" -f 2)
+              version=$(echo $file | cut -d "/" -f 2 | cut -d "-" -f 3)
+              found=$(jq --arg name "$name" --arg version "$version" '.playbooks[] | select(.name == $name and .version == $version)' $metadata_json_path)
+              if [[ -z $found ]]; then
+                  echo "Playbook $file with version $version not found in $metadata_json_path"
+                  exit 1
+              fi
+            fi
+          done
+
+
+
           
   Required_functions:
     name: Checking for required functions
