updated

diff --git a/.github/workflows/sanity_checks.yml b/.github/workflows/sanity_checks.yml
--- a/.github/workflows/sanity_checks.yml
+++ b/.github/workflows/sanity_checks.yml
@@ -26,17 +26,17 @@ jobs:
           done
           echo "MODIFIED_FILES=${{ env.MODIFIED_FILES }}" >> $GITHUB_ENV
       
-      - name: Filter added files
-        env:
-          ADDED_FILES: ${{ steps.changed-files.outputs.added }}
-        run: |
-            for file in "${{ env.ADDED_FILES }}"; do
-              echo "$file was changed"
-            done
-            echo "ADDED_FILES=${{ env.ADDED_FILES }}" >> $GITHUB_ENV        
+      # - name: Filter added files
+      #   env:
+      #     ADDED_FILES: ${{ steps.changed-files.outputs.added }}
+      #   run: |
+      #       for file in "${{ env.ADDED_FILES }}"; do
+      #         echo "$file was changed"
+      #       done
+      #       echo "ADDED_FILES=${{ env.ADDED_FILES }}" >> $GITHUB_ENV        
       
-      - name: Print files
-        run: echo "${{ env.ADDED_FILES }}"
+      # - name: Print files
+      #   run: echo "${{ env.ADDED_FILES }}"
 
      
       - name: Get the list of assessment tools
@@ -48,18 +48,18 @@ jobs:
       - run: echo "${{ env.ASSESSMENT_TOOLS }}"
       - name: Check if steps file present
         run: |
-          steps_flag=true
-          for file in $(echo "${{ env.MODIFIED_FILES }}" | grep -E "${{ env.ASSESSMENT_TOOLS }}" | grep ".*playbook.sh"); do
-            tool_name=$(echo "$file" | cut -d "-" -f 2)
-            version=$(echo "$file" | cut -d "-" -f 3)
-            if ! (echo "${{ env.MODIFIED_FILES }}" | grep "besman-$tool_name-$version-steps" || ls -R . | grep "besman-$tool_name-$version-steps"); then
-              steps_flag=false
-              echo -e "\e[31mCould not find steps file for \e[33mbesman-$tool_name-$version-playbook.sh\e[31m"
+          for file in $(echo "${{ env.MODIFIED_FILES }}"
+            if (echo $file | grep -E "${{ env.ASSESSMENT_TOOLS }}" | grep '\-playbook\.sh$')
+            then
+              tool_name=$(echo "$file" | cut -d "-" -f 2)
+              version=$(echo "$file" | cut -d "-" -f 3)
+              if ! (echo "${{ env.MODIFIED_FILES }}" | grep "besman-$tool_name-$version-steps" || ls -R . | grep "besman-$tool_name-$version-steps"); then
+                steps_flag=false
+                echo -e "\e[31mCould not find steps file for \e[33mbesman-$tool_name-$version-playbook.sh\e[31m"
+                exit 1
+              fi
             fi
           done
-          if [[ "$steps_flag" == "false" ]]; then
-            exit 1
-          fi
   File_Name_Standard:
     name: Check for file naming convention
     runs-on: ubuntu-latest
