Updated

diff --git a/.github/workflows/sanity_checks.yml b/.github/workflows/sanity_checks.yml
--- a/.github/workflows/sanity_checks.yml
+++ b/.github/workflows/sanity_checks.yml
@@ -3,8 +3,6 @@ name: Pull Request Checks
 on:
   pull_request:
     types: [opened, synchronize, reopened]
-  push:
-    branches: [dev]
 
 jobs:
   Required_files:
@@ -40,9 +38,27 @@ jobs:
 
       - name: Check if steps file present
         run: |
-          files=${{ env.MODIFIED_FILES }}
-          tools=${{ env.ASSESSMENT_TOOLS }}
-          source ./.github/scripts/file_check.sh "$files" "$tools"
+          steps_flag=true
+          for file in $(echo "${{ env.MODIFIED_FILES }}" | grep -E "${{ env.ASSESSMENT_TOOLS }}" | grep '\-playbook\.sh$'); do
+            tool_name=$(echo "$file" | cut -d "-" -f 2)
+            version=$(echo "$file" | cut -d "-" -f 3)
+            if echo "${{ env.MODIFIED_FILES }}" | grep -q "besman-$tool_name-$version-steps" && ls -R . | grep -q "besman-$tool_name-$version-steps"
+            then
+              steps_flag=false
+              echo -e "\e[31mCould not find steps file for \e[33mbesman-$tool_name-$version-playbook.sh\e[31m"
+            # elif ls -R . | grep -q "besman-$tool_name-$version-steps"
+            # then
+            #   steps_flag=false
+            fi
+            if [[ "$steps_flag" == "true" ]]
+            then
+                exit 1
+            fi
+          done
+          # if [[ "$steps_flag" == "true" ]]
+          # then
+          #   exit 1
+          # fi
 
 
   Required_functions:
@@ -91,9 +107,8 @@ jobs:
       - name: Check for required functions
         run: |
           function_flag=false
-          for file in $(echo "${{ env.MODIFIED_FILES }}" | grep -E "${{ env.ASSESSMENT_TOOLS }}" | grep '\-playbook.sh$'); do
+          for file in $(echo "${{ env.MODIFIED_FILES }}" | grep -E "${{ env.ASSESSMENT_TOOLS }}" | grep *playbook.sh'); do
             # Check if the file ends with "-playbook.sh"
-            echo "file=$file"
             for f in ${{ env.PLAYBOOK_FUNCTIONS }}; do
 
               if ! grep -q -w "function $f" $file
